current OCSP expiration check

diff --git a/hapos-upd b/hapos-upd
--- a/hapos-upd
+++ b/hapos-upd
@@ -7,7 +7,7 @@
 
 set -o nounset
 
-VERSION="0.1.0"
+VERSION="0.2.0"
 
 PROGNAME="hapos-upd"
 
@@ -36,12 +36,8 @@ function Quit() {
     exit $1
 }
 
-function Error() {
-    if [ $1 -eq 9 ]; then
-        MSG="Error: $2"
-    else
-        MSG="Error processing '$CERT': $2"
-    fi
+function LogError() {
+    MSG="$1"
 
     if [ -z "$SYSLOG_PRIO" ]; then
         echo "$MSG" >&2
@@ -50,6 +46,16 @@ function Error() {
     fi
 
     echo "$MSG" >>$TMP/log
+}
+
+function Error() {
+    if [ $1 -eq 9 ]; then
+        MSG="Error: $2"
+    else
+        MSG="Error processing '$CERT': $2"
+    fi
+
+    LogError "$MSG"
 
     if [ $1 -eq 9 ]; then
         echo "Run $PROGNAME -h for help" >&2
@@ -256,6 +262,32 @@ fi
 
 if [ -z "$CERT" ]; then
     Error 9 "certificate not provided (--cert argument)"
+fi
+
+# CURRENT RESPONSE EXPIRED?
+# ----------------------------------
+
+if [ -e $CERT.ocsp ]; then
+    Debug "An OCSP response already exists: checking its expiration."
+
+    $OPENSSL_BIN ocsp -respin $CERT.ocsp -text -noverify | \
+        grep "Next Update:" &>>$TMP/log
+
+    if [ $? -eq 0 ]; then
+        CURR_EXP=`$OPENSSL_BIN ocsp -respin $CERT.ocsp -text -noverify | grep "Next Update:" | cut -d ':' -f 2-`
+        CURR_EXP_EPOCH=`date --date="$CURR_EXP" +%s`
+
+        if [ $? -ne 0 ]; then
+            Error 3 "can't parse Next Update from current OCSP response"
+        fi
+
+        if [ $CURR_EXP_EPOCH -lt `date +%s` ]; then
+            Debug "Current OCSP response expiration: $CURR_EXP - expired"
+            LogError "current OCSP response is expired: please consider running this script more frequently"i
+        else
+            Debug "Current OCSP response expiration: $CURR_EXP - NOT expired"
+        fi
+    fi
 fi
 
 # EXTRACT EE CERTIFICATE INFO
